import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@clerk/react';
import { ClipboardCheck, Image, RefreshCw, ShieldCheck } from 'lucide-react';
import { PageHeading, EmptyState, StatusBadge } from '../App';
import { AccessGate } from './Authentication';
import { api, dateLabel, pollutantLabel, valueLabel } from './data';
import { ModelWorkspace } from './ModelExchange';
import LocalDevices from './LocalDevices';
import EarlyWarning from './EarlyWarning';
import { SpikeWorkspace } from './SuddenSpikes';

export default function Authority() { return <div className="page"><PageHeading eyebrow="AUTHORIZED OPERATIONS / INDIA AIR OUTLOOK" title="Early warning. Local response." description="Review forecast watches alongside ground evidence. Private case and device tools require an approved operator account." /><AccessGate authority><OperatorWorkspace /></AccessGate></div>; }
function OperatorWorkspace() {
  const { getToken } = useAuth(); const [tab, setTab] = useState('warnings');
  return <div><div className="authority-warning-tabs" aria-label="Operator workspace views"><button className={tab === 'warnings' ? 'active' : ''} onClick={() => setTab('warnings')} aria-pressed={tab === 'warnings'}>Early warnings</button><button className={tab === 'spikes' ? 'active' : ''} onClick={() => setTab('spikes')} aria-pressed={tab === 'spikes'}>Sudden spikes</button><button className={tab === 'cases' ? 'active' : ''} onClick={() => setTab('cases')} aria-pressed={tab === 'cases'}>Case review</button><button className={tab === 'models' ? 'active' : ''} onClick={() => setTab('models')} aria-pressed={tab === 'models'}>Model review</button><button className={tab === 'devices' ? 'active' : ''} onClick={() => setTab('devices')} aria-pressed={tab === 'devices'}>Local sensors</button></div>{tab === 'warnings' ? <EarlyWarning authority getToken={getToken} /> : tab === 'spikes' ? <SpikeWorkspace authority onReview={() => setTab('cases')} /> : <><div className="private-banner"><ShieldCheck size={18} /><span>Private evidence · Human review required · No government dispatch or external notification is connected.</span></div>{tab === 'cases' ? <CaseWorkspace getToken={getToken} /> : tab === 'devices' ? <LocalDevices getToken={getToken} /> : <ModelWorkspace getToken={getToken} />}</>}</div>;
}
function CaseWorkspace({ getToken }) {
  const [cases, setCases] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async signal => { setLoading(true); try { const token = await getToken(); if (!token) throw new Error('Your session expired. Please sign in again.'); const result = await api('/api/v2/authority/cases', { headers: { Authorization: `Bearer ${token}` }, signal }); setCases(result.cases || []); setError(''); } catch (err) { if (!signal?.aborted) { setCases([]); setError(err.message); } } finally { if (!signal?.aborted) setLoading(false); } }, [getToken]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); const timer = setInterval(() => load(controller.signal), 60000); return () => { controller.abort(); clearInterval(timer); }; }, [load]);
  return <div><div className="exchange-toolbar"><div><h2>Private review queue</h2><p>Submitted observations are supporting evidence. Review does not certify a pollution source.</p></div><button className="button secondary" onClick={() => load()} disabled={loading}><RefreshCw size={14} className={loading ? 'spin' : ''} />Refresh cases</button></div>{error ? <div className="notice danger" role="alert">{error}</div> : null}<div className="case-list">{cases.length ? cases.map(item => <CaseCard key={`${item.id}:${item.version}`} item={item} getToken={getToken} onChanged={() => load()} />) : <div className="panel"><EmptyState icon={ClipboardCheck} title={loading ? 'Loading private cases…' : error ? 'Case access unavailable' : 'The review queue is clear'}>{loading ? 'Checking authorized evidence records.' : error ? 'Private records have been cleared from this view.' : 'New consented community reports will appear here for human assessment.'}</EmptyState></div>}</div></div>;
}
function CaseCard({ item, getToken, onChanged }) {
  const [status, setStatus] = useState('under_review'); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [photo, setPhoto] = useState(''); const [events, setEvents] = useState(null);
  useEffect(() => () => { if (photo) URL.revokeObjectURL(photo); }, [photo]);
  const request = async (path, options = {}) => { const token = await getToken(); if (!token) throw new Error('Your session expired.'); return api(path, { ...options, headers: { Authorization: `Bearer ${token}`, ...(options.headers || {}) } }); };
  const save = async event => { event.preventDefault(); setBusy(true); setError(''); try { await request(`/api/v2/authority/cases/${encodeURIComponent(item.id)}/actions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, notes: notes.trim(), expected_version: item.version }) }); onChanged(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const loadPhoto = async () => { setBusy(true); setError(''); try { const token = await getToken(); if (!token) throw new Error('Your session expired.'); const base = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, ''); const response = await fetch(`${base}/api/v2/authority/cases/${encodeURIComponent(item.id)}/photo`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('The evidence photo is unavailable or access was denied.'); const blob = await response.blob(); if (!blob.type.startsWith('image/')) throw new Error('The evidence response was not an image.'); setPhoto(URL.createObjectURL(blob)); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const loadAudit = async () => { setError(''); try { const result = await request(`/api/v2/authority/cases/${encodeURIComponent(item.id)}/audit`); setEvents(result.events || []); } catch (err) { setError(err.message); } };
  return <article className="panel case-card"><div className="case-top"><h3>{item.id}</h3><StatusBadge status={item.status} /></div><p>{item.description || 'Evidence text is unavailable or withdrawn.'}</p><div className="case-meta"><span>{dateLabel(item.created_at)}</span><span>{item.kind?.replaceAll('_', ' ')}</span><span>Version {item.version}</span>{item.latitude != null && item.longitude != null ? <span>{Number(item.latitude).toFixed(3)}° N, {Number(item.longitude).toFixed(3)}° E</span> : null}</div>{item.reading ? <div className="notice amber"><span>Unverified {item.reading.environment} device · {pollutantLabel(item.reading.pollutant)} {valueLabel(item.reading.value)} {item.reading.unit} · {dateLabel(item.reading.observed_at)}</span></div> : null}<div className="form-actions" style={{ marginBottom: 19 }}>{item.has_photo ? <button className="button secondary" disabled={busy} onClick={loadPhoto}><Image size={14} />View private photo</button> : null}<button className="text-link" onClick={loadAudit}>View review history</button></div>{photo ? <img className="photo-preview" src={photo} alt="Private community evidence submitted for operator review" /> : null}{events ? <div className="import-preview"><h3>Review history</h3>{events.length ? events.map((event, index) => <p className="panel-note" key={event.id || index}>{dateLabel(event.created_at)} · {event.event_type || event.action || event.status} · {event.notes || event.note || 'Event recorded'}</p>) : <p className="panel-note">No review events available.</p>}</div> : null}{item.status !== 'withdrawn' ? <form className="case-form" onSubmit={save}><label className="field"><span>Next review state</span><select value={status} onChange={e => setStatus(e.target.value)}><option value="under_review">Under review</option><option value="needs_verification">Needs verification</option><option value="closed">Close review</option></select></label><label className="field"><span>Decision notes</span><textarea required minLength={5} maxLength={2000} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Record the evidence checked, uncertainty and next action." /></label><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Record decision'}</button></form> : null}{error ? <p className="inline-message error" role="alert">{error}</p> : null}</article>;
}
