import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownToLine, ArrowUpRight, FileJson, Globe2, RefreshCw, ShieldCheck, Upload } from 'lucide-react';
import { PageHeading, EmptyState, StatusBadge } from '../App';
import { api, pollutantLabel, valueLabel } from './data';

const requiredFields = ['schema_version', 'name', 'version', 'country_code', 'region', 'parameter', 'unit', 'horizon_hours', 'metrics', 'holdout_start', 'holdout_end', 'license', 'privacy_notes', 'training_data_summary', 'model_family'];
export default function ModelExchange() { return <div className="page"><PageHeading eyebrow="BRICS / GOVERNED MODEL INTERCHANGE" title="Share the learning. Keep the context." description="Explore reviewed model cards and exchange versioned metadata with provenance, evaluation and privacy boundaries." /><div className="exchange-intro"><div><span className="eyebrow">INTEROPERABLE BY DESIGN</span><h2>Local evidence.<br />A shared language.</h2><p>Exchange model descriptions, evaluation metrics and data-use conditions in one reviewable format. This pilot has no connected partner countries or federated training rounds.</p></div><div className="exchange-symbol" aria-hidden="true"><span className="exchange-globe"><Globe2 size={76} strokeWidth={.7} /></span><span className="exchange-code">PROVENANCE → REVIEW → EXCHANGE</span></div></div><ModelWorkspace /><div className="evidence-boundary"><ShieldCheck size={18} /><div><strong>Metadata travels only after review.</strong><p>A checksum checks content integrity. It does not certify model validity, partner identity or government approval. No resident records, model executables or private device data are included.</p></div></div></div>; }

export function ModelWorkspace({ getToken }) {
  const privateView = Boolean(getToken);
  const [models, setModels] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [preview, setPreview] = useState(null); const [fileName, setFileName] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const fileInput = useRef(null);
  const load = useCallback(async signal => { setLoading(true); try { const headers = {}; if (getToken) { const token = await getToken(); if (!token) throw new Error('Your session has expired.'); headers.Authorization = `Bearer ${token}`; } const response = await api(privateView ? '/api/v2/authority/models' : '/api/v2/models', { headers, signal }); setModels(response.models || []); setError(''); } catch (err) { if (!signal?.aborted) { setModels([]); setError(err.message); } } finally { if (!signal?.aborted) setLoading(false); } }, [getToken, privateView]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const inspect = async file => { setError(''); setMessage(''); setPreview(null); if (!file) return; try { if (file.size > 26000) throw new Error('Use a JSON metadata file no larger than 26 KB including its envelope.'); const value = JSON.parse(await file.text()); const metadata = value.metadata || value; if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) throw new Error('The file must contain a model metadata object.'); const missing = requiredFields.filter(key => !(key in metadata)); if (missing.length) throw new Error(`Missing metadata fields: ${missing.join(', ')}.`); if (metadata.schema_version !== '1.0') throw new Error('This exchange accepts metadata schema 1.0.'); if (Object.keys(metadata).some(key => !requiredFields.includes(key) && key !== 'artifact_sha256')) throw new Error('Unsupported fields found. Only documented metadata fields are accepted.'); if (value.metadata && Object.keys(value).some(key => !['schema_version', 'metadata', 'metadata_checksum_sha256'].includes(key))) throw new Error('Unsupported interchange envelope fields.'); setPreview(value); setFileName(file.name); } catch (err) { setError(err.message); } finally { if (fileInput.current) fileInput.current.value = ''; } };
  const importModel = async () => { setBusy(true); setError(''); try { const token = await getToken(); if (!token) throw new Error('Please sign in again.'); await api('/api/v2/authority/models', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(preview) }); setPreview(null); setMessage('Metadata submitted to the private review queue. It is not published or deployed.'); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const exportModel = async model => { setError(''); try { const envelope = await api(`/api/v2/models/${encodeURIComponent(model.id)}/export`); const url = URL.createObjectURL(new Blob([JSON.stringify(envelope, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `vayunirikshak-model-${model.id}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (err) { setError(err.message); } };
  return <div><div className="exchange-toolbar"><div><h2>{privateView ? 'Model review workspace' : 'Reviewed model registry'}</h2><p>{privateView ? 'Imported metadata requires an explicit review before public exchange.' : 'Only operator-approved model metadata appears here.'}</p></div><div className="form-actions" style={{ marginTop: 0 }}><button className="icon-button" onClick={() => load()} disabled={loading} aria-label="Refresh model registry"><RefreshCw size={16} className={loading ? 'spin' : ''} /></button><button className="button secondary" onClick={() => fileInput.current?.click()}><Upload size={14} />{privateView ? 'Import model card' : 'Inspect a model card'}</button><input ref={fileInput} className="sr-only" type="file" accept="application/json,.json" onChange={e => inspect(e.target.files?.[0])} /></div></div>{error ? <div className="notice danger" role="alert">{error}</div> : null}{message ? <div className="notice" role="status">{message}</div> : null}{preview ? <div className="import-preview"><h3><FileJson size={15} /> {fileName}</h3><p className="panel-note">Required metadata fields are present. The server checks units, evaluation dates, metrics and any checksum before accepting it.</p><pre>{JSON.stringify(preview, null, 2)}</pre><div className="form-actions">{privateView ? <button className="button primary" disabled={busy} onClick={importModel}><ShieldCheck size={14} />{busy ? 'Submitting…' : 'Submit for operator review'}</button> : <Link to="/authority" className="button secondary">Operator sign-in required to submit <ArrowUpRight size={14} /></Link>}<button className="text-link" onClick={() => setPreview(null)}>Close preview</button></div></div> : null}<div className="model-list">{models.length ? models.map(model => <ModelCard key={model.id} model={model} exportModel={exportModel} getToken={getToken} onChanged={() => load()} />) : <section className="panel"><EmptyState icon={Globe2} title={loading ? 'Loading model registry…' : error ? 'Model registry is unavailable' : 'No reviewed models have been published'}>{loading ? 'Checking the metadata registry.' : 'Model cards appear after evaluation, provenance and privacy review. You can inspect a supplied metadata file locally.'}</EmptyState></section>}</div><details className="evidence-boundary"><summary>Model card format · schema 1.0</summary><p>Required fields: {requiredFields.join(', ')}. Metrics require MAE and RMSE from a completed chronological holdout. Country is a two-letter code; concentrations use ug/m3 (or mg/m3 for CO). An optional artifact_sha256 identifies an artifact without uploading executable content.</p></details></div>;
}
function ModelCard({ model, exportModel, getToken, onChanged }) {
  const card = model.metadata || model; const [notes, setNotes] = useState(''); const [decision, setDecision] = useState('approve'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const review = async event => { event.preventDefault(); setBusy(true); setError(''); try { const token = await getToken(); if (!token) throw new Error('Your session has expired.'); await api(`/api/v2/authority/models/${encodeURIComponent(model.id)}/review`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ approve: decision === 'approve', notes: notes.trim(), expected_version: model.version }) }); onChanged(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <article className="panel model-card"><div className="model-card-head"><div><span className="eyebrow">{card.country_code} / {card.region}</span><h3>{card.name}</h3><p>{card.model_family} · version {card.version}</p></div><StatusBadge status={model.status}>{model.status}</StatusBadge></div><dl className="model-details"><div><dt>Target & horizon</dt><dd>{pollutantLabel(card.parameter)} · {card.horizon_hours}h · {card.unit}</dd></div><div><dt>Holdout evaluation</dt><dd>MAE {valueLabel(card.metrics?.mae)} · RMSE {valueLabel(card.metrics?.rmse)}</dd></div><div><dt>Evaluation window</dt><dd>{card.holdout_start} → {card.holdout_end}</dd></div><div><dt>Data provenance</dt><dd>{card.training_data_summary}</dd></div><div><dt>License</dt><dd>{card.license}</dd></div><div><dt>Privacy conditions</dt><dd>{card.privacy_notes}</dd></div></dl>{model.status === 'approved' ? <button className="button secondary" onClick={() => exportModel(model)}><ArrowDownToLine size={14} />Export reviewed metadata</button> : null}{getToken && model.status === 'pending_review' ? <form className="case-form" onSubmit={review}><label className="field"><span>Review decision</span><select value={decision} onChange={e => setDecision(e.target.value)}><option value="approve">Approve metadata</option><option value="reject">Reject metadata</option></select></label><label className="field"><span>Review rationale</span><textarea required minLength={5} maxLength={2000} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Record provenance, holdout and privacy checks." /></label><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Record review'}</button></form> : null}{error ? <div className="inline-message error" role="alert">{error}</div> : null}</article>;
}
