"""AirSentinel authority-review prototype; run separately from the public view."""

from pathlib import Path

import pandas as pd
import streamlit as st

from src.api.schemas import CaseActionInput
from src.api.security import authority_dashboard_production_ready, is_production_mode
from src.services.case_audit import (
    overlay_review_state,
    read_case_actions,
    save_case_action,
)
from src.services.gemini_explainer import explain_case


st.set_page_config(page_title="AirSentinel Authority", page_icon="🛡️", layout="wide")

if is_production_mode() and not authority_dashboard_production_ready():
    st.error(
        "Authority review is disabled in production until this Streamlit view is "
        "deployed as a private Cloud Run service with an approved IAM invoker group "
        "and the explicit authority-review safeguards enabled. Use the authenticated "
        "API or an approved authority portal instead."
    )
    st.stop()

CASE_FILE = Path("data/processed/authority_case_queue.csv")
LOCALITY_FILE = Path("data/processed/locality_evidence_profile.csv")
COMMUNITY_SIGNAL_FILE = Path("data/processed/community_signal_summary.csv")
MODEL_READINESS_FILE = Path("data/processed/model_promotion_readiness.csv")
LOCALITY_FORECAST_FILE = Path(
    "data/processed/locality_multi_horizon_latest_forecast.csv"
)

st.title("🛡️ AirSentinel — Authority Review Prototype")
st.warning(
    "Decision support only. This prototype does not provide official AQI, source "
    "attribution, automated enforcement, or access to any government system."
)

if not CASE_FILE.exists():
    st.info(
        "No authority queue has been generated yet. Run the locality and anomaly "
        "pipeline first."
    )
else:
    cases = pd.read_csv(CASE_FILE)
    cases = pd.DataFrame(overlay_review_state(cases.to_dict(orient="records")))
    case_col1, case_col2, case_col3 = st.columns(3)
    case_col1.metric(
        "Cases not closed",
        int(cases["review_state"].fillna("open").ne("closed").sum()),
    )
    case_col2.metric(
        "Unexpected-spike reviews",
        int(
            cases["case_category"].isin(
                ["unexpected spike review", "unexpected local spike review"]
            ).sum()
        ),
    )
    case_col3.metric(
        "Coverage-review cases",
        int(cases["case_category"].eq("local evidence coverage review").sum()),
    )

    st.subheader("Human-review case queue")
    st.dataframe(cases, width="stretch", hide_index=True)

    if not cases.empty:
        selected_case_id = st.selectbox("Inspect a case", cases["case_id"])
        selected_case = cases.loc[cases["case_id"].eq(selected_case_id)].iloc[0]
        st.subheader(f"Case: {selected_case['case_id']}")
        st.write(f"**Area:** {selected_case['area_name']}")
        st.write(f"**Evidence:** {selected_case['evidence_summary']}")
        st.write(f"**Recommended action:** {selected_case['recommended_action']}")
        st.write(f"**Latest prototype review state:** {selected_case['review_state']}")
        st.caption(selected_case["review_state_limit"])
        st.caption(selected_case["automation_limit"])

        if st.button("Generate guarded case explanation", key=f"explain-{selected_case_id}"):
            explanation, generated_by = explain_case(selected_case.to_dict())
            st.info(explanation)
            st.caption(f"Generated by: {generated_by}")

        st.subheader("Record prototype review action")
        if is_production_mode():
            st.info(
                "Production authority actions are view-only in this Streamlit "
                "prototype. Submit reviewed actions through the private FastAPI "
                "endpoint or an approved authority portal so the authenticated "
                "identity and server-side role policy are enforced."
            )
        else:
            st.caption(
                "Local demonstration only. Use a role, not a person's name. This "
                "writes an ephemeral local audit note and does not contact an "
                "authority or trigger an external action."
            )
            with st.form(f"case-action-{selected_case_id}"):
                action_col1, action_col2 = st.columns(2)
                actor_role = action_col1.selectbox(
                    "Reviewer role",
                    [
                        "data reviewer",
                        "environment analyst",
                        "field verification coordinator",
                        "prototype administrator",
                    ],
                )
                action_type = action_col2.selectbox(
                    "Review action",
                    [
                        "acknowledged",
                        "evidence review started",
                        "field check requested",
                        "resolved - insufficient evidence",
                        "closed after authorised review",
                    ],
                )
                outcome_status = action_col1.selectbox(
                    "Case status after this note",
                    ["open", "awaiting evidence", "review in progress", "closed"],
                )
                review_note = st.text_area(
                    "Review note (optional; do not include names, phone numbers or addresses)",
                    max_chars=500,
                )
                action_saved = st.form_submit_button("Save prototype audit action")

            if action_saved:
                record = save_case_action(
                    selected_case_id,
                    CaseActionInput(
                        actor_role=actor_role,
                        action_type=action_type,
                        outcome_status=outcome_status,
                        review_note=review_note,
                    ),
                )
                st.success(f"Saved local audit action {record['action_id']}.")
                st.rerun()

        saved_actions = read_case_actions(selected_case_id)
        if saved_actions:
            st.dataframe(pd.DataFrame(saved_actions), width="stretch", hide_index=True)

if LOCALITY_FILE.exists():
    locality_profile = pd.read_csv(LOCALITY_FILE)
    locality_profile = locality_profile.loc[
        locality_profile["area_type"].eq("locality")
    ]
    st.subheader("Locality evidence status")
    locality_columns = [
        "area_name",
        "pollutant_code",
        "hourly_observations",
        "reporting_stations",
        "freshness_hours_at_download",
        "nearest_station_distance_metres",
        "spatial_resolution",
        "median_measurement_coverage_percent",
        "evidence_status",
    ]
    st.dataframe(
        locality_profile[
            [column for column in locality_columns if column in locality_profile]
        ],
        width="stretch",
        hide_index=True,
    )

if COMMUNITY_SIGNAL_FILE.exists():
    community_signals = pd.read_csv(COMMUNITY_SIGNAL_FILE)
    st.subheader("Privacy-preserving community corroboration")
    st.caption(
        "Aggregate moderation signals only. Raw report text, contact details and "
        "coarse location references are not displayed here.")
    community_col1, community_col2, community_col3 = st.columns(3)
    community_col1.metric(
        "Reports stored for moderation",
        int(community_signals["reports_total"].fillna(0).sum()),
    )
    community_col2.metric(
        "Recent corroboration candidates",
        int(community_signals["reports_last_6h"].fillna(0).ge(2).sum()),
    )
    community_col3.metric(
        "Localities with any report",
        int(community_signals["reports_total"].fillna(0).gt(0).sum()),
    )
    st.dataframe(
        community_signals[
            [
                "area_name",
                "reports_total",
                "reports_pending_moderation",
                "reports_last_6h",
                "corroboration_status",
                "automation_limit",
            ]
        ].rename(
            columns={
                "area_name": "Locality",
                "reports_total": "Reports stored",
                "reports_pending_moderation": "Awaiting moderation",
                "reports_last_6h": "Reports in last 6 hours",
                "corroboration_status": "Review status",
                "automation_limit": "Limit",
            }
        ),
        width="stretch",
        hide_index=True,
    )

if MODEL_READINESS_FILE.exists():
    model_readiness = pd.read_csv(MODEL_READINESS_FILE)
    locality_readiness = model_readiness.loc[
        model_readiness["area_type"].eq("locality")
    ]
    st.subheader("Model-promotion evidence gate")
    st.caption(
        "This prevents a locality deep-learning claim before it has adequate local "
        "history, station coverage and multi-pollutant evidence.")
    readiness_columns = [
        "area_name",
        "pm25_hourly_rows",
        "pm25_completeness_percent",
        "pm25_reporting_stations",
        "core_pollutant_codes",
        "historical_evaluation_status",
        "historical_evaluation_horizons",
        "baseline_gate",
        "advanced_model_gate",
        "advanced_model_next_step",
    ]
    st.dataframe(
        locality_readiness[
            [column for column in readiness_columns if column in locality_readiness]
        ].rename(
            columns={
                "area_name": "Locality",
                "pm25_hourly_rows": "PM2.5 hourly rows",
                "pm25_completeness_percent": "PM2.5 completeness (%)",
                "pm25_reporting_stations": "PM2.5 stations",
                "core_pollutant_codes": "Core pollutants",
                "historical_evaluation_status": "Historical evaluation",
                "historical_evaluation_horizons": "Evaluated horizons",
                "baseline_gate": "Baseline-model gate",
                "advanced_model_gate": "Advanced-model gate",
                "advanced_model_next_step": "Required next step",
            }
        ),
        width="stretch",
        hide_index=True,
    )

if LOCALITY_FORECAST_FILE.exists():
    locality_forecasts = pd.read_csv(LOCALITY_FORECAST_FILE)
    if not locality_forecasts.empty:
        st.subheader("Locality forecast research outputs")
        st.caption(
            "Historical prototype outputs only. Check freshness, empirical range and "
            "the model gate before using them as supporting evidence in a case.")
        forecast_columns = [
            "area_name",
            "horizon",
            "input_time_utc",
            "forecast_for_utc",
            "current_pm25_input",
            "predicted_pm25",
            "selected_model",
            "empirical_interval_low",
            "empirical_interval_high",
            "forecast_status",
        ]
        st.dataframe(
            locality_forecasts[
                [column for column in forecast_columns if column in locality_forecasts]
            ],
            width="stretch",
            hide_index=True,
        )

st.caption(
    "Before a field action, a reviewer must check station freshness, coverage, "
    "context evidence, jurisdiction and the appropriate official process."
)
