"""Privacy-safe local citizen-report prototype for AirSentinel."""

from pathlib import Path

import pandas as pd
import streamlit as st

from src.api.schemas import CommunityReportInput
from src.cloud.language_services import transcribe_audio
from src.services.community_reports import save_local_report
from src.services.gemini_photo import analyse_photo


st.set_page_config(page_title="AirSentinel Report", page_icon="🗣️", layout="centered")

AREAS_FILE = Path("data/reference/monitoring_areas.csv")
areas = pd.read_csv(AREAS_FILE)
localities = areas.loc[areas["area_type"].eq("locality")].copy()

st.title("🗣️ Report local air conditions")
st.caption(
    "Your report supports human review. It is not an official AQI measurement, "
    "and one report cannot identify a pollution source or trigger enforcement."
)

st.subheader("Optional accessible evidence")
photo = st.file_uploader(
    "Photo (JPEG, PNG, or WebP; processed in memory)",
    type=["jpg", "jpeg", "png", "webp"],
    help="The raw photo is not stored by this local prototype.",
)
if photo is not None and st.button("Create a review description from photo"):
    try:
        description, generated_by = analyse_photo(photo.getvalue(), photo.type)
    except ValueError as error:
        st.error(str(error))
    else:
        st.session_state["citizen_evidence_text"] = description
        st.info(f"{description}\n\nGenerated by: {generated_by}. Human moderation required.")

audio = st.file_uploader(
    "Voice note (optional WAV, MP3, or OGG; requires configured Speech-to-Text)",
    type=["wav", "mp3", "ogg"],
)
if audio is not None and st.button("Transcribe voice note"):
    try:
        transcript = transcribe_audio(audio.getvalue(), "hi-IN", audio.type)
    except (RuntimeError, ValueError):
        st.warning("Speech-to-Text is not configured. Type a short observation below.")
    else:
        st.session_state["citizen_evidence_text"] = transcript
        st.info("Transcript created for human review; retain the original only under the approved consent policy.")

with st.form("community-report"):
    locality_name = st.selectbox("Nearest pilot locality", localities["area_name"])
    source_type = st.selectbox(
        "Report type",
        ["text", "voice_transcript", "photo_description"],
        help="Voice and photos are represented as reviewed descriptions until approved cloud services are configured.",
    )
    language_code = st.selectbox("Language", ["en", "hi", "ta", "bn", "mr", "kn"])
    report_text = st.text_area(
        "What did you observe?",
        max_chars=1000,
        value=st.session_state.get("citizen_evidence_text", ""),
        placeholder="Example: Strong smoke smell near the road since 7 PM.",
    )
    coarse_location_cell = st.text_input(
        "Optional coarse ward/grid reference",
        max_chars=80,
        help="Do not enter your home address, phone number, email, or exact GPS location.",
    )
    consent = st.checkbox("I consent to storing this report for moderation and research.")
    submitted = st.form_submit_button("Submit for human review")

if submitted:
    selected = localities.loc[localities["area_name"].eq(locality_name)].iloc[0]
    try:
        record = save_local_report(
            CommunityReportInput(
                locality_id=selected["area_id"],
                report_text=report_text,
                language_code=language_code,
                source_type=source_type,
                consent_to_store=consent,
                coarse_location_cell=coarse_location_cell or None,
            )
        )
    except ValueError as error:
        st.error(str(error))
    else:
        st.success(f"Report {record['report_id']} saved for moderation.")
        st.caption("Status: unverified community evidence; no source attribution is made.")

st.info(
    "When enabled in an approved Google Cloud project, Firebase stores the redacted "
    "moderation record, Speech-to-Text creates a consented transcript, Translation "
    "creates a review-language copy, and Gemini can describe submitted images. Every "
    "output remains supporting evidence, not a confirmed measurement."
)
